# This package contains pregenerated soong.variables files for the aosp_<arch> products.
# They're used to make platforms for testing in soong_injection. This is an optimization, we could
# generate these directly from source at build time but it would add time to every `m nothing`.
# Converting the product config makefiles to starlark and checking them in would also solve this
# performance issue.
