load(":apex_diff_test.bzl", "apex_diff_test")

apex_diff_test(
    name = "com.android.tzdata",
    apex1 = "@make_injection//:target/product/generic/system/apex/com.android.tzdata.apex",
    apex2 = "//system/timezone/apex:com.android.tzdata",
)
